In [30]:
import numpy as np
import time
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print('vectorize version:' + str(1000*(toc-tic)) + "ms")


249691.557694
vectorize version:26.208162307739258ms


In [4]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop: " + str(1000*(toc-tic)) + "ms")

249691.557694
For loop: 439.133882522583ms


In [5]:
yo = np.random.rand(10)
print(yo)

[ 0.60498013  0.36862763  0.53140688  0.69241215  0.93897921  0.99012892
  0.25477557  0.69720785  0.46137064  0.77156311]


In [6]:
print(yo)

[ 0.60498013  0.36862763  0.53140688  0.69241215  0.93897921  0.99012892
  0.25477557  0.69720785  0.46137064  0.77156311]


In [7]:
# J = 0, dw1 = 0, dw2 = 0, db = 0

In [8]:
# def draw_me_a_cat(w, b, num_iterations = 2000, learning_rate = 0.5, print_cost = False):
#     """
#     Draws a sample cat as it was learned by the neural network.
#     """
    
#     w = d["w"]
#     b = d["b"]
#     X = np.random.rand(w.shape[0], 1)
    
#     for i in range(num_iterations):
#         A = sigmoid(np.dot(w.T, X) + b)
#         cost = -np.log(A)
    
#         dx = np.dot(w, (A - 1).T)

#         X -= learning_rate * dx
        
#         # Print the cost every 100 iterations
#         if print_cost and i % 100 == 0:
#             print ("Cost after iteration %i: %f" %(i, cost))
    
#     return X
    
# cat = draw_me_a_cat(d["w"], d["b"], num_iterations = 10000, learning_rate = 0.005, print_cost = True)

# plt.imshow(cat.reshape((num_px, num_px, 3)))

# cat_prediction = predict(d["w"], d["b"], cat)
# print("y = " + str(np.squeeze(cat_prediction)) + ", your algorithm predicts a \"" + classes[int(np.squeeze(cat_prediction)),].decode("utf-8") +  "\" picture.")

In [29]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
cal = A.sum(axis=0)
cal #array([59, 239, 155.4, 76.9])
# A.sum() #530.3000007
percentage = A/cal.reshape(1,4) #take matrix A and divide 1 by 4 matrix. ex of python broadcasting, take matrix
#A and divide by 1 by 4 matrix. technically don't need to use reshape since cal is already a 1x4 matrix. reshape is
#cheap to call 
percentage

array([[ 0.94915254,  0.        ,  0.02831403,  0.88426528],
       [ 0.02033898,  0.43514644,  0.33462033,  0.10403121],
       [ 0.03050847,  0.56485356,  0.63706564,  0.01170351]])

In [17]:
# l = np.linspace(0,2,10)
# l

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667,  0.88888889,
        1.11111111,  1.33333333,  1.55555556,  1.77777778,  2.        ])

In [18]:
# sum = 0
# for idx in l:
#     sum += idx
# print(sum)

10.0


In [45]:
tes = np.random.randn(5) #don't use something that comes witha (5,)
# 
tes.shape #rank 1 array//neither a row or column vector
tes #array([ 0.13423209,  1.20856596, -0.69983161, -1.38260042,  0.16761682])

array([-0.97707091,  1.12766865,  0.81031367,  0.35086816, -1.09848312])

In [37]:
tes.T

array([ 0.13423209,  1.20856596, -0.69983161, -1.38260042,  0.16761682])

In [49]:
np.dot(tes,tes.T)

4.2126860299378777

In [50]:
tes2 = np.random.randn(5,1)
tes2 #array([[-0.08350992],
#        [ 1.99557866],
#        [-0.96903789],
#        [ 0.62662542],
#        [-0.40100085]])
        

IndentationError: unexpected indent (<ipython-input-50-0afacf7c12c0>, line 3)

In [52]:
np.dot(tes2,tes2.T) #gives outter product of vector

array([[ 0.00697391, -0.16665061,  0.08092427, -0.05232944,  0.03348755],
       [-0.16665061,  3.9823342 , -1.93379134,  1.25048032, -0.80022874],
       [ 0.08092427, -1.93379134,  0.93903444, -0.60722378,  0.38858502],
       [-0.05232944,  1.25048032, -0.60722378,  0.39265942, -0.25127733],
       [ 0.03348755, -0.80022874,  0.38858502, -0.25127733,  0.16080168]])